if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'christoomey/vim-tmux-navigator'
Plug 'sgur/vim-editorconfig'
Plug 'janko-m/vim-test'
Plug 'ludovicchabant/vim-gutentags'
Plug 'mattn/emmet-vim'
Plug 'sheerun/vim-polyglot'
Plug 'tommcdo/vim-lion'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline'
Plug 'w0rp/ale'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'kana/vim-textobj-user'
Plug 'coderifous/textobj-word-column.vim'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'tek/vim-textobj-ruby'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vim-emoji'
Plug 'maralla/completor.vim'
Plug 'ternjs/tern_for_vim'
Plug 'tmux-plugins/vim-tmux'

call plug#end()

let mapleader = " "

filetype plugin indent on
syntax on

runtime macros/matchit.vim

set autoread
set autowrite
set autoindent
set backspace=indent,eol,start  " Allow backspacing over everything in insert mode.
set clipboard=unnamed
set colorcolumn=81,101          " Highlight where 80 and 100 characters are
set diffopt+=vertical
set display=truncate            " show @@@ in the last line if it is truncated.
set hidden
set history=500
set ignorecase
set incsearch
set laststatus=2                " Always show the status line
set list listchars=tab:»\ ,trail:·,nbsp:·,extends:›,precedes:‹
set nobackup
set noshowmode
set nowritebackup
set noswapfile
set number
set undolevels=1000
set ruler                       " show the cursor position all the time
set scrolloff=3                 " Show a few lines of context around the cursor.
set showcmd                     " display incomplete commands
set ttimeout
set ttimeoutlen=100             " wait up to 100ms after Esc for special key
set wildmenu                    " display completion matches in a status line

" 2 space tabs
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

if has('mouse')
  set mouse=a
endif

set termguicolors     " Enable true color support
set background=dark
colorscheme ayu

" Enable italics
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
set t_ut=


" Persistent undo
let undodir = expand('~/.undo-vim')
if !isdirectory(undodir)
  call mkdir(undodir)
endif
set undodir=~/.undo-vim
set undofile  " Create FILE.un~ files for persistent undo

" Switch between the last two files
nnoremap <leader><leader> <c-^>

" Grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" Quicker window movement
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" Save file with <c-s>
nnoremap <c-s> <Esc>:w<CR>
vnoremap <c-s> <Esc><c-s>gv
inoremap <c-s> <Esc><c-s>

" hide and delete buffer
nnoremap <c-x><c-u> :bunload<cr>
nnoremap <c-x><c-d> :bdelete<cr>

" zoom a vim pane, <C-w>= to re-balance
nnoremap <leader>- :wincmd _<cr>:wincmd \|<cr>
nnoremap <leader>= :wincmd =<cr>

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" ======================================
" plugins
" ======================================
" use ripgrep for grep
if executable('rg')
  set grepprg=rg\ --vimgrep
  set grepformat=%f:%l:%c:%m
endif

" vim-test
let test#strategy = "dispatch"

nmap <silent> <leader>tn :TestNearest<CR>
nmap <silent> <leader>tf :TestFile<CR>
nmap <silent> <leader>ta :TestSuite<CR>
nmap <silent> <leader>tl :TestLast<CR>
nmap <silent> <leader>tv :TestVisit<CR>

" airline
let g:airline_powerline_fonts = 1
let g:airline_mode_map = { 'n': 'N', 'i' : 'I', 'R': 'R', 'v': 'V', 'V': 'V' }
" let g:airline_left_sep = ''
" let g:airline_right_sep = ''
" let g:airline_left_alt_sep = '|'
" let g:airline_right_alt_sep = '|'

" emmet
imap <c-e> <plug>(emmet-expand-abbr)

" ALE
let g:ale_sign_column_always = 1
let g:ale_javascript_eslint_use_global = 1
if emoji#available()
  let g:ale_sign_error = emoji#for('sos')
  let g:ale_sign_warning = emoji#for('vibration_mode')
endif

" fzf.vim
nnoremap <c-p> :Files<cr>
imap <c-x><c-l> <plug>(fzf-complete-line)
imap <c-x><c-f> <plug>(fzf-complete-path)

nnoremap <silent> <leader>B :Buffers<CR>
nnoremap <silent> <leader>W :Windows<CR>
nnoremap <silent> <leader>; :BLines<CR>
nnoremap <silent> <leader>[ :BTags<CR>
nnoremap <silent> <leader>] :Tags<CR>
nnoremap <silent> <leader>? :History<CR>

" vim-commentary
nmap cm <Plug>Commentary

" editorconfig
let g:EditorConfig_exclude_patterns = ['fugitive://.*']

map <leader>H :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<' . synIDattr(synID(line("."),col("."),0),"name") . "> lo<" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">" . " FG:" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"fg#")<CR>
